site_name: Data File Utils
theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [data_file_utils]
nav:
  - Home: index.md
  - Installation: INSTALL.md
  - Code Reference:
  # INSERT CODE REFERENCE SECTION
    - Analyze Record Tuples: analyze_record_tuples.md
    - Archive Directory: archive_dir.md
    - Backup Directory: backup_dir.md
    - Backup File: backup_file.md
    - Compare Tab-delimited Files: compare_tab_files.md
    - Console Helper: console_helper.md
    - Convert Excel to Tab-delimited: xlsx2tsv.md
    - Convert JSONL to JSON: jsonl2json.md
    - Convert Tab-delimited to JSON: tsv2json.md
    - Create Temporary Directory: create_tmp_dir.md
    - Delete Users Files: delete_users_files.md
    - File Utils: file_utils.md
    - Find Last Directory: find_last_directory.md
    - Find Last File: find_last_file.md
    - Profile Data File: profile_data_file.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/jai-python3"  target="_blank" rel="noopener">Jai Python3</a>
